/*! IlmuAlam Quran SW | version 554097d6e0 | generated by tools/build.py, do not edit sw.js directly */
"use strict";
const VER = "554097d6e0";
const SHELL = "ilmq-shell-" + VER;
const DATA = "ilmq-data-v1"; // surah JSON rarely changes; kept across deploys and refreshed in the background
const PRE = ["./", "dasar-privasi.html", "assets/js/quran-home.js", "assets/fonts/amiri-arabic-400-normal.woff2", "manifest.webmanifest", "favicon.ico", "assets/icons/logo-64.webp", "assets/icons/favicon-96.png", "assets/icons/icon-192.png", "assets/icons/icon-512.png"];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(SHELL).then(c => c.addAll(PRE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith("ilmq-") && k !== SHELL && k !== DATA).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function fresh(req, cacheName) {
  return fetch(req).then(res => {
    if (res.ok && res.type === "basic") {
      const copy = res.clone();
      caches.open(cacheName).then(c => c.put(req, copy));
    }
    return res;
  });
}

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return; // audio streams from everyayah.com stay network-only

  // pages: network first so new deploys show immediately, cached shell when offline
  if (req.mode === "navigate") {
    e.respondWith(
      fresh(req, SHELL).catch(() =>
        caches.match(req, { ignoreSearch: true }).then(r => r || caches.match("./"))
      )
    );
    return;
  }

  // everything else same-origin: cache first, revalidate in the background
  const bucket = url.pathname.includes("/data-surah/") ? DATA : SHELL;
  e.respondWith(
    caches.match(req).then(hit => {
      const net = fresh(req, bucket);
      if (hit) {
        e.waitUntil(net.catch(() => {}));
        return hit;
      }
      return net;
    })
  );
});
