/*! Ilmu Alam surah CTA | adds a "read & listen" box to surah articles on www.ilmualam.com | generated by tools/build.py */
(()=>{"use strict";
const M={{MAP}};
const m=M[location.pathname];
if(!m||document.querySelector(".ilmq-cta"))return;
const body=document.querySelector(".post-body,.entry-content,.post-entry,.post-content");
if(!body)return;
const [n,name,ar,ayat]=m,url="{{SITE}}#surah-"+n;

const css=document.createElement("style");
css.textContent=`.ilmq-cta,.ilmq-cta *{box-sizing:border-box}
.ilmq-cta{display:grid;grid-template-columns:1fr auto;align-items:center;gap:10px 16px;margin:20px 0;padding:16px 18px;border-radius:16px;background:linear-gradient(135deg,#1a7038,#0c3808);color:#fff;font:400 15px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;box-shadow:0 8px 20px rgba(12,56,8,.18)}
.ilmq-cta__title{margin:0;font-size:17px;font-weight:800;line-height:1.35;color:#fff}
.ilmq-cta__ar{font-family:"Amiri","Traditional Arabic",serif;font-weight:400;font-size:20px;margin-left:6px}
.ilmq-cta__desc{margin:4px 0 0;font-size:14px;color:#e2f6e8}
.ilmq-cta__btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:10px 18px;border-radius:12px;background:#fff;color:#0c3808!important;font-weight:800;text-decoration:none!important;white-space:nowrap}
.ilmq-cta__btn:hover{background:#eaf5ed}
@media(max-width:560px){.ilmq-cta{grid-template-columns:1fr}.ilmq-cta__btn{width:100%}}`;
document.head.appendChild(css);

const box=document.createElement("aside");
box.className="ilmq-cta";
box.setAttribute("aria-label","Baca dan dengar Surah "+name);
box.innerHTML=`<div><p class="ilmq-cta__title">🎧 Baca &amp; Dengar Surah ${name}<span class="ilmq-cta__ar" lang="ar" dir="rtl">${ar}</span></p><p class="ilmq-cta__desc">${ayat} ayat penuh: teks Arab, Rumi, terjemahan Melayu &amp; audio 5 qari. Percuma, tanpa daftar.</p></div><a class="ilmq-cta__btn" href="${url}">Baca &amp; Dengar ›</a>`;

// before the first subheading keeps the box below the fold on most posts, so it never shifts what the reader is looking at
const h=body.querySelector("h2,h3");
h?h.parentNode.insertBefore(box,h):body.appendChild(box);
})();
