# (arabic, rumi, malay meaning, starting juz)
S = [
(),
("الفاتحة","Al-Fatihah","Pembukaan",1),
("البقرة","Al-Baqarah","Lembu Betina",1),
("آل عمران","Ali 'Imran","Keluarga Imran",3),
("النساء","An-Nisa'","Wanita",4),
("المائدة","Al-Ma'idah","Hidangan",6),
("الأنعام","Al-An'am","Binatang Ternakan",7),
("الأعراف","Al-A'raf","Tempat Tertinggi",8),
("الأنفال","Al-Anfal","Harta Rampasan Perang",9),
("التوبة","At-Taubah","Taubat",10),
("يونس","Yunus","Nabi Yunus",11),
("هود","Hud","Nabi Hud",11),
("يوسف","Yusuf","Nabi Yusuf",12),
("الرعد","Ar-Ra'd","Guruh",13),
("إبراهيم","Ibrahim","Nabi Ibrahim",13),
("الحجر","Al-Hijr","Hijr (Kawasan Thamud)",14),
("النحل","An-Nahl","Lebah",14),
("الإسراء","Al-Isra'","Perjalanan Malam",15),
("الكهف","Al-Kahfi","Gua",15),
("مريم","Maryam","Maryam",16),
("طه","Taha","Taha",16),
("الأنبياء","Al-Anbiya'","Para Nabi",17),
("الحج","Al-Hajj","Haji",17),
("المؤمنون","Al-Mu'minun","Orang-orang Mukmin",18),
("النور","An-Nur","Cahaya",18),
("الفرقان","Al-Furqan","Pembeza",18),
("الشعراء","Asy-Syu'ara'","Para Penyair",19),
("النمل","An-Naml","Semut",19),
("القصص","Al-Qasas","Kisah-kisah",20),
("العنكبوت","Al-'Ankabut","Labah-labah",20),
("الروم","Ar-Rum","Bangsa Rom",21),
("لقمان","Luqman","Luqman",21),
("السجدة","As-Sajdah","Sujud",21),
("الأحزاب","Al-Ahzab","Golongan yang Bersekutu",21),
("سبأ","Saba'","Negeri Saba'",22),
("فاطر","Fatir","Pencipta",22),
("يس","Yasin","Yasin",22),
("الصافات","As-Saffat","Yang Berbaris-baris",23),
("ص","Sad","Sad",23),
("الزمر","Az-Zumar","Rombongan-rombongan",23),
("غافر","Ghafir","Yang Mengampunkan",24),
("فصلت","Fussilat","Yang Dijelaskan",24),
("الشورى","Asy-Syura","Musyawarah",25),
("الزخرف","Az-Zukhruf","Perhiasan Emas",25),
("الدخان","Ad-Dukhan","Asap",25),
("الجاثية","Al-Jathiyah","Yang Berlutut",25),
("الأحقاف","Al-Ahqaf","Bukit Pasir",26),
("محمد","Muhammad","Nabi Muhammad",26),
("الفتح","Al-Fath","Kemenangan",26),
("الحجرات","Al-Hujurat","Bilik-bilik",26),
("ق","Qaf","Qaf",26),
("الذاريات","Adz-Dzariyat","Angin yang Menerbangkan",26),
("الطور","At-Tur","Bukit Tursina",27),
("النجم","An-Najm","Bintang",27),
("القمر","Al-Qamar","Bulan",27),
("الرحمن","Ar-Rahman","Yang Maha Pemurah",27),
("الواقعة","Al-Waqi'ah","Hari Kiamat",27),
("الحديد","Al-Hadid","Besi",27),
("المجادلة","Al-Mujadilah","Wanita yang Mengadu",28),
("الحشر","Al-Hasyr","Pengusiran",28),
("الممتحنة","Al-Mumtahanah","Wanita yang Diuji",28),
("الصف","As-Saff","Barisan",28),
("الجمعة","Al-Jumu'ah","Hari Jumaat",28),
("المنافقون","Al-Munafiqun","Orang-orang Munafik",28),
("التغابن","At-Taghabun","Hari Dinampakkan Kerugian",28),
("الطلاق","At-Talaq","Talak",28),
("التحريم","At-Tahrim","Pengharaman",28),
("الملك","Al-Mulk","Kerajaan",29),
("القلم","Al-Qalam","Pena",29),
("الحاقة","Al-Haqqah","Hari Kiamat yang Pasti",29),
("المعارج","Al-Ma'arij","Tempat-tempat Naik",29),
("نوح","Nuh","Nabi Nuh",29),
("الجن","Al-Jinn","Jin",29),
("المزمل","Al-Muzzammil","Orang yang Berselimut",29),
("المدثر","Al-Muddaththir","Orang yang Berkemul",29),
("القيامة","Al-Qiyamah","Hari Kiamat",29),
("الإنسان","Al-Insan","Manusia",29),
("المرسلات","Al-Mursalat","Malaikat yang Diutus",29),
("النبأ","An-Naba'","Berita Besar",30),
("النازعات","An-Nazi'at","Malaikat yang Mencabut",30),
("عبس","'Abasa","Dia Bermasam Muka",30),
("التكوير","At-Takwir","Menggulung",30),
("الانفطار","Al-Infitar","Terbelah",30),
("المطففين","Al-Mutaffifin","Orang yang Curang",30),
("الانشقاق","Al-Insyiqaq","Terbelah",30),
("البروج","Al-Buruj","Gugusan Bintang",30),
("الطارق","At-Tariq","Yang Datang di Waktu Malam",30),
("الأعلى","Al-A'la","Yang Maha Tinggi",30),
("الغاشية","Al-Ghasyiyah","Hari Pembalasan",30),
("الفجر","Al-Fajr","Fajar",30),
("البلد","Al-Balad","Negeri",30),
("الشمس","Asy-Syams","Matahari",30),
("الليل","Al-Lail","Malam",30),
("الضحى","Ad-Duha","Waktu Dhuha",30),
("الشرح","Al-Insyirah","Kelapangan",30),
("التين","At-Tin","Buah Tin",30),
("العلق","Al-'Alaq","Segumpal Darah",30),
("القدر","Al-Qadr","Kemuliaan",30),
("البينة","Al-Bayyinah","Bukti yang Nyata",30),
("الزلزلة","Az-Zalzalah","Kegoncangan",30),
("العاديات","Al-'Adiyat","Kuda Perang yang Berlari Kencang",30),
("القارعة","Al-Qari'ah","Hari yang Menggemparkan",30),
("التكاثر","At-Takathur","Bermegah-megah",30),
("العصر","Al-'Asr","Masa",30),
("الهمزة","Al-Humazah","Pengumpat",30),
("الفيل","Al-Fil","Gajah",30),
("قريش","Quraisy","Suku Quraisy",30),
("الماعون","Al-Ma'un","Barang yang Berguna",30),
("الكوثر","Al-Kauthar","Nikmat yang Banyak",30),
("الكافرون","Al-Kafirun","Orang-orang Kafir",30),
("النصر","An-Nasr","Pertolongan",30),
("المسد","Al-Masad","Sabut",30),
("الإخلاص","Al-Ikhlas","Ikhlas",30),
("الفلق","Al-Falaq","Waktu Subuh",30),
("الناس","An-Nas","Manusia",30),
]
assert len(S) == 115
MADANI = {2,3,4,5,8,9,13,22,24,33,47,48,49,55,57,58,59,60,61,62,63,64,65,66,76,98,99,110}
ALIAS = {
 1:"fatihah fatiha pembukaan alfatihah ummulkitab",2:"baqarah baqara",3:"imran aliimran",4:"nisa nisaa",
 5:"maidah maaidah",9:"taubah tawbah baraah",18:"kahf kahfi kahaf",19:"maryam mariam",36:"yasin yaasin yaseen yassin",
 55:"rahman arrahman",56:"waqiah waqiyah",67:"mulk tabarak",73:"muzammil muzzammil",74:"mudathir muddatsir",
 94:"insyirah sharh alamnasyrah",93:"dhuha duha",108:"kautsar kausar kawthar",112:"ikhlas ikhlash",
 113:"falaq",114:"nas naas",103:"asr",105:"fiil fil",106:"quraisy quraish",107:"maun",
}
POPULAR = [1,2,18,36,55,56,67,112]


# Full article on www.ilmualam.com for each surah (used for card links, ItemList JSON-LD, llms.txt and the Blogger CTA map)
ARTICLES = {
 1: "https://www.ilmualam.com/2020/03/surah-al-fatihah-rumi.html",
 2: "https://www.ilmualam.com/2020/03/surah-al-baqarah.html",
 3: "https://www.ilmualam.com/2020/03/surah-ali-imran.html",
 4: "https://www.ilmualam.com/2020/04/surah-an-nisa.html",
 5: "https://www.ilmualam.com/2020/05/surah-al-maidah.html",
 6: "https://www.ilmualam.com/2026/01/surah-al-anam.html",
 7: "https://www.ilmualam.com/2026/01/surah-al-araf.html",
 8: "https://www.ilmualam.com/2025/12/surah-al-anfal-rumi.html",
 9: "https://www.ilmualam.com/2026/09/surah-at-taubah.html",
 10: "https://www.ilmualam.com/2025/12/surah-yunus-rumi.html",
 11: "https://www.ilmualam.com/2025/12/surah-hud-rumi.html",
 12: "https://www.ilmualam.com/2025/11/surah-yusuf.html",
 13: "https://www.ilmualam.com/2026/09/surah-ar-rad.html",
 14: "https://www.ilmualam.com/2026/03/surah-ibrahim.html",
 15: "https://www.ilmualam.com/2025/12/surah-al-hijr-rumi.html",
 16: "https://www.ilmualam.com/2025/12/surah-an-nahl.html",
 17: "https://www.ilmualam.com/2025/12/surah-al-isra-rumi.html",
 18: "https://www.ilmualam.com/2025/11/surah-al-kahfi-rumi.html",
 19: "https://www.ilmualam.com/2022/02/surah-maryam.html",
 20: "https://www.ilmualam.com/2025/11/surah-taha-rumi.html",
 21: "https://www.ilmualam.com/2025/12/surah-al-anbiya-rumi.html",
 22: "https://www.ilmualam.com/2025/12/surah-al-hajj-rumi.html",
 23: "https://www.ilmualam.com/2026/09/surah-al-mukminun.html",
 24: "https://www.ilmualam.com/2026/09/surah-an-nur.html",
 25: "https://www.ilmualam.com/2025/12/surah-al-furqan.html",
 26: "https://www.ilmualam.com/2025/12/surah-asy-syuara-rumi.html",
 27: "https://www.ilmualam.com/2026/02/surah-an-naml.html",
 28: "https://www.ilmualam.com/2025/12/surah-al-qasas-rumi.html",
 29: "https://www.ilmualam.com/2026/09/surah-al-ankabut.html",
 30: "https://www.ilmualam.com/2026/03/surah-ar-rum.html",
 31: "https://www.ilmualam.com/2026/01/surah-luqman.html",
 32: "https://www.ilmualam.com/2026/01/surah-as-sajdah.html",
 33: "https://www.ilmualam.com/2025/12/surah-al-ahzab.html",
 34: "https://www.ilmualam.com/2025/12/surah-saba.html",
 35: "https://www.ilmualam.com/2025/12/surah-al-fatir.html",
 36: "https://www.ilmualam.com/2020/05/surah-yassin.html",
 37: "https://www.ilmualam.com/2025/12/surah-as-saffat.html",
 38: "https://www.ilmualam.com/2026/02/surah-saad.html",
 39: "https://www.ilmualam.com/2026/01/surah-az-zumar.html",
 40: "https://www.ilmualam.com/2026/01/surah-ghafir.html",
 41: "https://www.ilmualam.com/2025/12/surah-fussilat.html",
 42: "https://www.ilmualam.com/2026/09/surah-asy-syura.html",
 43: "https://www.ilmualam.com/2026/02/surah-az-zukhruf.html",
 44: "https://www.ilmualam.com/2026/01/surah-ad-dukhan.html",
 45: "https://www.ilmualam.com/2026/02/surah-al-jaathiyah.html",
 46: "https://www.ilmualam.com/2026/02/surah-al-ahqaf.html",
 47: "https://www.ilmualam.com/2026/01/surah-muhammad.html",
 48: "https://www.ilmualam.com/2026/02/surah-al-fath.html",
 49: "https://www.ilmualam.com/2026/01/surah-al-hujurat.html",
 50: "https://www.ilmualam.com/2026/01/surah-qaaf.html",
 51: "https://www.ilmualam.com/2026/01/surah-adh-dhariyat.html",
 52: "https://www.ilmualam.com/2026/02/surah-at-tur.html",
 53: "https://www.ilmualam.com/2026/03/surah-najm.html",
 54: "https://www.ilmualam.com/2026/02/surah-al-qamar.html",
 55: "https://www.ilmualam.com/2025/11/surah-ar-rahman.html",
 56: "https://www.ilmualam.com/2025/11/surah-al-waqiah.html",
 57: "https://www.ilmualam.com/2026/01/surah-al-hadid.html",
 58: "https://www.ilmualam.com/2026/01/surah-al-mujadilah.html",
 59: "https://www.ilmualam.com/2026/01/surah-al-hashr.html",
 60: "https://www.ilmualam.com/2026/02/surah-al-mumtahanah.html",
 61: "https://www.ilmualam.com/2026/02/surah-as-saff.html",
 62: "https://www.ilmualam.com/2026/01/surah-al-jumuah.html",
 63: "https://www.ilmualam.com/2026/01/surah-al-munafiqun.html",
 64: "https://www.ilmualam.com/2026/02/surah-at-taghaabun.html",
 65: "https://www.ilmualam.com/2026/03/surah-at-talaq.html",
 66: "https://www.ilmualam.com/2026/01/surah-at-tahrim.html",
 67: "https://www.ilmualam.com/2020/05/surah-al-mulk.html",
 68: "https://www.ilmualam.com/2026/01/surah-al-qalam.html",
 69: "https://www.ilmualam.com/2026/01/surah-al-haqqah.html",
 70: "https://www.ilmualam.com/2026/03/surah-al-maaarij.html",
 71: "https://www.ilmualam.com/2026/01/surah-nuh.html",
 72: "https://www.ilmualam.com/2025/12/surah-al-jinn-rumi.html",
 73: "https://www.ilmualam.com/2025/12/surah-al-muzzammil-rumi.html",
 74: "https://www.ilmualam.com/2026/02/surah-al-muddaththir.html",
 75: "https://www.ilmualam.com/2026/01/surah-al-qiyamah.html",
 76: "https://www.ilmualam.com/2026/01/surah-al-insaan.html",
 77: "https://www.ilmualam.com/2026/01/surah-al-mursalaat.html",
 78: "https://www.ilmualam.com/2026/01/surah-an-naba.html",
 79: "https://www.ilmualam.com/2026/03/surah-an-naziat.html",
 80: "https://www.ilmualam.com/2026/01/surah-abasa.html",
 81: "https://www.ilmualam.com/2026/02/surah-at-takwir.html",
 82: "https://www.ilmualam.com/2026/02/surah-al-infitar.html",
 83: "https://www.ilmualam.com/2026/02/surah-al-mutaffifin.html",
 84: "https://www.ilmualam.com/2026/03/surah-al-inshiqaq.html",
 85: "https://www.ilmualam.com/2026/02/surah-al-buruj.html",
 86: "https://www.ilmualam.com/2026/02/surah-at-tariq.html",
 87: "https://www.ilmualam.com/2026/02/surah-al-alaa.html",
 88: "https://www.ilmualam.com/2026/02/surah-al-ghashiyah.html",
 89: "https://www.ilmualam.com/2026/02/surah-al-fajr.html",
 90: "https://www.ilmualam.com/2026/02/surah-al-balad.html",
 91: "https://www.ilmualam.com/2026/02/surah-asy-syams.html",
 92: "https://www.ilmualam.com/2026/02/surah-al-lail.html",
 93: "https://www.ilmualam.com/2025/12/surah-ad-dhuha-rumi.html",
 94: "https://www.ilmualam.com/2026/03/surah-ash-sharh.html",
 95: "https://www.ilmualam.com/2026/02/surah-at-tin.html",
 96: "https://www.ilmualam.com/2026/03/surah-al-alaq.html",
 97: "https://www.ilmualam.com/2025/12/surah-al-qadr-rumi.html",
 98: "https://www.ilmualam.com/2026/03/surah-al-bayyinah.html",
 99: "https://www.ilmualam.com/2026/03/surah-al-zalzalah.html",
 100: "https://www.ilmualam.com/2026/03/surah-al-adiyat.html",
 101: "https://www.ilmualam.com/2026/03/surah-al-qariah.html",
 102: "https://www.ilmualam.com/2026/03/surah-at-takathur.html",
 103: "https://www.ilmualam.com/2026/03/surah-al-asr.html",
 104: "https://www.ilmualam.com/2026/03/surah-al-humazah.html",
 105: "https://www.ilmualam.com/2026/03/surah-al-fiil.html",
 106: "https://www.ilmualam.com/2026/03/surah-quraisy.html",
 107: "https://www.ilmualam.com/2026/03/surah-al-maun.html",
 108: "https://www.ilmualam.com/2026/03/surah-al-kautsar.html",
 109: "https://www.ilmualam.com/2025/11/surah-al-kafirun-rumi.html",
 110: "https://www.ilmualam.com/2026/03/surah-an-nasr.html",
 111: "https://www.ilmualam.com/2026/03/surah-al-masad.html",
 112: "https://www.ilmualam.com/2025/12/surah-al-ikhlas-rumi.html",
 113: "https://www.ilmualam.com/2025/12/surah-al-falaq-rumi.html",
 114: "https://www.ilmualam.com/2025/12/surah-an-nas-rumi.html",
}
