# (arabic, rumi, malay meaning, starting juz)
S = [
(),
("الفاتحة","Al-Fatihah","Pembukaan",1),
("البقرة","Al-Baqarah","Lembu Betina",1),
("آل عمران","Ali 'Imran","Keluarga Imran",3),
("النساء","An-Nisa'","Wanita",4),
("المائدة","Al-Ma'idah","Hidangan",6),
("الأنعام","Al-An'am","Binatang Ternakan",7),
("الأعراف","Al-A'raf","Tempat Tertinggi",8),
("الأنفال","Al-Anfal","Harta Rampasan Perang",9),
("التوبة","At-Taubah","Taubat",10),
("يونس","Yunus","Nabi Yunus",11),
("هود","Hud","Nabi Hud",11),
("يوسف","Yusuf","Nabi Yusuf",12),
("الرعد","Ar-Ra'd","Guruh",13),
("إبراهيم","Ibrahim","Nabi Ibrahim",13),
("الحجر","Al-Hijr","Hijr (Kawasan Thamud)",14),
("النحل","An-Nahl","Lebah",14),
("الإسراء","Al-Isra'","Perjalanan Malam",15),
("الكهف","Al-Kahfi","Gua",15),
("مريم","Maryam","Maryam",16),
("طه","Taha","Taha",16),
("الأنبياء","Al-Anbiya'","Para Nabi",17),
("الحج","Al-Hajj","Haji",17),
("المؤمنون","Al-Mu'minun","Orang-orang Mukmin",18),
("النور","An-Nur","Cahaya",18),
("الفرقان","Al-Furqan","Pembeza",18),
("الشعراء","Asy-Syu'ara'","Para Penyair",19),
("النمل","An-Naml","Semut",19),
("القصص","Al-Qasas","Kisah-kisah",20),
("العنكبوت","Al-'Ankabut","Labah-labah",20),
("الروم","Ar-Rum","Bangsa Rom",21),
("لقمان","Luqman","Luqman",21),
("السجدة","As-Sajdah","Sujud",21),
("الأحزاب","Al-Ahzab","Golongan yang Bersekutu",21),
("سبأ","Saba'","Negeri Saba'",22),
("فاطر","Fatir","Pencipta",22),
("يس","Yasin","Yasin",22),
("الصافات","As-Saffat","Yang Berbaris-baris",23),
("ص","Sad","Sad",23),
("الزمر","Az-Zumar","Rombongan-rombongan",23),
("غافر","Ghafir","Yang Mengampunkan",24),
("فصلت","Fussilat","Yang Dijelaskan",24),
("الشورى","Asy-Syura","Musyawarah",25),
("الزخرف","Az-Zukhruf","Perhiasan Emas",25),
("الدخان","Ad-Dukhan","Asap",25),
("الجاثية","Al-Jathiyah","Yang Berlutut",25),
("الأحقاف","Al-Ahqaf","Bukit Pasir",26),
("محمد","Muhammad","Nabi Muhammad",26),
("الفتح","Al-Fath","Kemenangan",26),
("الحجرات","Al-Hujurat","Bilik-bilik",26),
("ق","Qaf","Qaf",26),
("الذاريات","Adz-Dzariyat","Angin yang Menerbangkan",26),
("الطور","At-Tur","Bukit Tursina",27),
("النجم","An-Najm","Bintang",27),
("القمر","Al-Qamar","Bulan",27),
("الرحمن","Ar-Rahman","Yang Maha Pemurah",27),
("الواقعة","Al-Waqi'ah","Hari Kiamat",27),
("الحديد","Al-Hadid","Besi",27),
("المجادلة","Al-Mujadilah","Wanita yang Mengadu",28),
("الحشر","Al-Hasyr","Pengusiran",28),
("الممتحنة","Al-Mumtahanah","Wanita yang Diuji",28),
("الصف","As-Saff","Barisan",28),
("الجمعة","Al-Jumu'ah","Hari Jumaat",28),
("المنافقون","Al-Munafiqun","Orang-orang Munafik",28),
("التغابن","At-Taghabun","Hari Dinampakkan Kerugian",28),
("الطلاق","At-Talaq","Talak",28),
("التحريم","At-Tahrim","Pengharaman",28),
("الملك","Al-Mulk","Kerajaan",29),
("القلم","Al-Qalam","Pena",29),
("الحاقة","Al-Haqqah","Hari Kiamat yang Pasti",29),
("المعارج","Al-Ma'arij","Tempat-tempat Naik",29),
("نوح","Nuh","Nabi Nuh",29),
("الجن","Al-Jinn","Jin",29),
("المزمل","Al-Muzzammil","Orang yang Berselimut",29),
("المدثر","Al-Muddaththir","Orang yang Berkemul",29),
("القيامة","Al-Qiyamah","Hari Kiamat",29),
("الإنسان","Al-Insan","Manusia",29),
("المرسلات","Al-Mursalat","Malaikat yang Diutus",29),
("النبأ","An-Naba'","Berita Besar",30),
("النازعات","An-Nazi'at","Malaikat yang Mencabut",30),
("عبس","'Abasa","Dia Bermasam Muka",30),
("التكوير","At-Takwir","Menggulung",30),
("الانفطار","Al-Infitar","Terbelah",30),
("المطففين","Al-Mutaffifin","Orang yang Curang",30),
("الانشقاق","Al-Insyiqaq","Terbelah",30),
("البروج","Al-Buruj","Gugusan Bintang",30),
("الطارق","At-Tariq","Yang Datang di Waktu Malam",30),
("الأعلى","Al-A'la","Yang Maha Tinggi",30),
("الغاشية","Al-Ghasyiyah","Hari Pembalasan",30),
("الفجر","Al-Fajr","Fajar",30),
("البلد","Al-Balad","Negeri",30),
("الشمس","Asy-Syams","Matahari",30),
("الليل","Al-Lail","Malam",30),
("الضحى","Ad-Duha","Waktu Dhuha",30),
("الشرح","Al-Insyirah","Kelapangan",30),
("التين","At-Tin","Buah Tin",30),
("العلق","Al-'Alaq","Segumpal Darah",30),
("القدر","Al-Qadr","Kemuliaan",30),
("البينة","Al-Bayyinah","Bukti yang Nyata",30),
("الزلزلة","Az-Zalzalah","Kegoncangan",30),
("العاديات","Al-'Adiyat","Kuda Perang yang Berlari Kencang",30),
("القارعة","Al-Qari'ah","Hari yang Menggemparkan",30),
("التكاثر","At-Takathur","Bermegah-megah",30),
("العصر","Al-'Asr","Masa",30),
("الهمزة","Al-Humazah","Pengumpat",30),
("الفيل","Al-Fil","Gajah",30),
("قريش","Quraisy","Suku Quraisy",30),
("الماعون","Al-Ma'un","Barang yang Berguna",30),
("الكوثر","Al-Kauthar","Nikmat yang Banyak",30),
("الكافرون","Al-Kafirun","Orang-orang Kafir",30),
("النصر","An-Nasr","Pertolongan",30),
("المسد","Al-Masad","Sabut",30),
("الإخلاص","Al-Ikhlas","Ikhlas",30),
("الفلق","Al-Falaq","Waktu Subuh",30),
("الناس","An-Nas","Manusia",30),
]
assert len(S) == 115
MADANI = {2,3,4,5,8,9,13,22,24,33,47,48,49,55,57,58,59,60,61,62,63,64,65,66,76,98,99,110}
ALIAS = {
 1:"fatihah fatiha pembukaan alfatihah ummulkitab",2:"baqarah baqara",3:"imran aliimran",4:"nisa nisaa",
 5:"maidah maaidah",9:"taubah tawbah baraah",18:"kahf kahfi kahaf",19:"maryam mariam",36:"yasin yaasin yaseen yassin",
 55:"rahman arrahman",56:"waqiah waqiyah",67:"mulk tabarak",73:"muzammil muzzammil",74:"mudathir muddatsir",
 94:"insyirah sharh alamnasyrah",93:"dhuha duha",108:"kautsar kausar kawthar",112:"ikhlas ikhlash",
 113:"falaq",114:"nas naas",103:"asr",105:"fiil fil",106:"quraisy quraish",107:"maun",
}
POPULAR = [1,2,18,36,55,56,67,112]
